name: austerity
description: Really strict static code analysis for Flutter and Dart
version: 0.0.1-beta
repository: https://github.com/MelbourneDeveloper/austerity

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
